import {
  Bell,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Chrome,
  Github,
  Heart,
  Languages,
  Laptop,
  Loader2,
  LogOut,
  MessageCircle,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Paintbrush,
  Plus,
  Repeat,
  Search,
  Send,
  Settings,
  Settings2,
  Sun,
  Trash2,
  User,
  UserMinus,
  UserPlus,
  UserX,
  XCircle
} from 'lucide-react'

export type { LucideIcon as IconType } from 'lucide-react'

export const Icons = {
  bell: Bell,
  checkCircle: CheckCircle2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  google: Chrome,
  github: Github,
  heart: Heart,
  languages: Languages,
  laptop: Laptop,
  logout: LogOut,
  message: MessageCircle,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  paintbrush: Paintbrush,
  plus: Plus,
  repeat: Repeat,
  search: Search,
  send: Send,
  settings: Settings,
  settings2: Settings2,
  spinner: Loader2,
  sun: Sun,
  trash: Trash2,
  user: User,
  userMinus: UserMinus,
  userPlus: UserPlus,
  userX: UserX,
  xCircle: XCircle
}
